### ISSUE TITLE
The Link is not working 

### ISSUE THREAD

**Issue by satoti** [KnowWhereGraph/hierarchical-cell-features#1]
I am trying to get access to the link : https://github.com/KnowWhereGraph/hierarchical-cell-features/blob/master/papers/hierarchical-cell-features-paper.pdf. I want to read this article please ??? could you please direct me how to get access to this pdf

**Comment by cogan-shimizu** [comment]
https://dl.acm.org/doi/fullHtml/10.1145/3502223.3502236
